# ===============================================================
# 🧪  PyTest & Coverage - Quality Gate
# ===============================================================
#
#   - runs the full test-suite across three Python versions
#   - measures branch + line coverage (fails < 40 %)
#   - uploads the XML/HTML coverage reports as build artifacts
#   - (optionally) generates / commits an SVG badge - kept disabled
#   - posts a concise per-file coverage table to the job summary
#   - executes on every push / PR to *main*  ➕  a weekly cron
# ---------------------------------------------------------------

name: Tests & Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # schedule:
  #   - cron: '42 3 * * 1'   # Monday 03:42 UTC

permissions:
  contents: write # needed *only* if the badge-commit step is enabled
  checks: write
  actions: read

jobs:
  async-testing:
    name: 🔄 Async Safety & Performance Testing
    runs-on: ubuntu-latest
    needs: [test]
    
    strategy:
      fail-fast: false
      matrix:
        python: ["3.11", "3.12"]

    steps:
      - name: ⬇️  Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: 🐍  Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          
      - name: 📦  Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install flake8-async flake8-bugbear pytest-asyncio snakeviz aiomonitor
          
      - name: 🔍  Run async linting
        run: |
          make async-lint
          
      - name: 🐛  Run async debug tests
        run: |
          make async-debug
          
      - name: 📊  Generate performance profiles
        run: |
          make profile
          
      - name: ⚡  Run async benchmarks
        run: |
          make async-benchmark
          
      - name: ✅  Validate async patterns
        run: |
          make async-validate
          
      - name: 📎  Upload async test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: async-test-results
          path: |
            async_testing/reports/
            async_testing/profiles/
          retention-days: 30
          
      - name: 📈  Performance regression check
        run: |
          python async_testing/check_regression.py \
            --current async_testing/profiles/latest.prof \
            --baseline async_testing/profiles/baseline.prof \
            --threshold 20  # 20% regression threshold

